// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/test.proto

package org.deephacks.vals.proto;

public final class ProtoMessages {
  private ProtoMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code org.deephacks.jenc.TimeUnit}
   */
  public enum TimeUnit
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SECONDS = 1;</code>
     */
    SECONDS(0, 1),
    /**
     * <code>MINUTES = 2;</code>
     */
    MINUTES(1, 2),
    ;

    /**
     * <code>SECONDS = 1;</code>
     */
    public static final int SECONDS_VALUE = 1;
    /**
     * <code>MINUTES = 2;</code>
     */
    public static final int MINUTES_VALUE = 2;


    public final int getNumber() { return value; }

    public static TimeUnit valueOf(int value) {
      switch (value) {
        case 1: return SECONDS;
        case 2: return MINUTES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TimeUnit>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TimeUnit>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TimeUnit>() {
            public TimeUnit findValueByNumber(int number) {
              return TimeUnit.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.deephacks.vals.proto.ProtoMessages.getDescriptor().getEnumTypes().get(0);
    }

    private static final TimeUnit[] VALUES = values();

    public static TimeUnit valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TimeUnit(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.deephacks.jenc.TimeUnit)
  }

  public interface Val5MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .org.deephacks.jenc.TimeUnit mobileInfo = 1;
    /**
     * <code>optional .org.deephacks.jenc.TimeUnit mobileInfo = 1;</code>
     */
    boolean hasMobileInfo();
    /**
     * <code>optional .org.deephacks.jenc.TimeUnit mobileInfo = 1;</code>
     */
    org.deephacks.vals.proto.ProtoMessages.TimeUnit getMobileInfo();

    // optional string value = 2;
    /**
     * <code>optional string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>optional string value = 2;</code>
     */
    String getValue();
    /**
     * <code>optional string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();

    // optional int32 id = 3;
    /**
     * <code>optional int32 id = 3;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 3;</code>
     */
    int getId();

    // repeated string strings = 4;
    /**
     * <code>repeated string strings = 4;</code>
     */
    java.util.List<String>
    getStringsList();
    /**
     * <code>repeated string strings = 4;</code>
     */
    int getStringsCount();
    /**
     * <code>repeated string strings = 4;</code>
     */
    String getStrings(int index);
    /**
     * <code>repeated string strings = 4;</code>
     */
    com.google.protobuf.ByteString
        getStringsBytes(int index);
  }
  /**
   * Protobuf type {@code org.deephacks.jenc.Val5Message}
   */
  public static final class Val5Message extends
      com.google.protobuf.GeneratedMessage
      implements Val5MessageOrBuilder {
    // Use Val5Message.newBuilder() to construct.
    private Val5Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Val5Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Val5Message defaultInstance;
    public static Val5Message getDefaultInstance() {
      return defaultInstance;
    }

    public Val5Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Val5Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.deephacks.vals.proto.ProtoMessages.TimeUnit value = org.deephacks.vals.proto.ProtoMessages.TimeUnit.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                mobileInfo_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              id_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                strings_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              strings_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          strings_ = new com.google.protobuf.UnmodifiableLazyStringList(strings_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.deephacks.vals.proto.ProtoMessages.internal_static_org_deephacks_jenc_Val5Message_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.deephacks.vals.proto.ProtoMessages.internal_static_org_deephacks_jenc_Val5Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.deephacks.vals.proto.ProtoMessages.Val5Message.class, org.deephacks.vals.proto.ProtoMessages.Val5Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Val5Message> PARSER =
        new com.google.protobuf.AbstractParser<Val5Message>() {
      public Val5Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Val5Message(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Val5Message> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .org.deephacks.jenc.TimeUnit mobileInfo = 1;
    public static final int MOBILEINFO_FIELD_NUMBER = 1;
    private org.deephacks.vals.proto.ProtoMessages.TimeUnit mobileInfo_;
    /**
     * <code>optional .org.deephacks.jenc.TimeUnit mobileInfo = 1;</code>
     */
    public boolean hasMobileInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .org.deephacks.jenc.TimeUnit mobileInfo = 1;</code>
     */
    public org.deephacks.vals.proto.ProtoMessages.TimeUnit getMobileInfo() {
      return mobileInfo_;
    }

    // optional string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private Object value_;
    /**
     * <code>optional string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string value = 2;</code>
     */
    public String getValue() {
      Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 id = 3;
    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    /**
     * <code>optional int32 id = 3;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 id = 3;</code>
     */
    public int getId() {
      return id_;
    }

    // repeated string strings = 4;
    public static final int STRINGS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList strings_;
    /**
     * <code>repeated string strings = 4;</code>
     */
    public java.util.List<String>
        getStringsList() {
      return strings_;
    }
    /**
     * <code>repeated string strings = 4;</code>
     */
    public int getStringsCount() {
      return strings_.size();
    }
    /**
     * <code>repeated string strings = 4;</code>
     */
    public String getStrings(int index) {
      return strings_.get(index);
    }
    /**
     * <code>repeated string strings = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStringsBytes(int index) {
      return strings_.getByteString(index);
    }

    private void initFields() {
      mobileInfo_ = org.deephacks.vals.proto.ProtoMessages.TimeUnit.SECONDS;
      value_ = "";
      id_ = 0;
      strings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, mobileInfo_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, id_);
      }
      for (int i = 0; i < strings_.size(); i++) {
        output.writeBytes(4, strings_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, mobileInfo_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < strings_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(strings_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getStringsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.deephacks.vals.proto.ProtoMessages.Val5Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deephacks.vals.proto.ProtoMessages.Val5Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deephacks.vals.proto.ProtoMessages.Val5Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deephacks.vals.proto.ProtoMessages.Val5Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deephacks.vals.proto.ProtoMessages.Val5Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.deephacks.vals.proto.ProtoMessages.Val5Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.deephacks.vals.proto.ProtoMessages.Val5Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.deephacks.vals.proto.ProtoMessages.Val5Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.deephacks.vals.proto.ProtoMessages.Val5Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.deephacks.vals.proto.ProtoMessages.Val5Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.deephacks.vals.proto.ProtoMessages.Val5Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.deephacks.jenc.Val5Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.deephacks.vals.proto.ProtoMessages.Val5MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.deephacks.vals.proto.ProtoMessages.internal_static_org_deephacks_jenc_Val5Message_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.deephacks.vals.proto.ProtoMessages.internal_static_org_deephacks_jenc_Val5Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.deephacks.vals.proto.ProtoMessages.Val5Message.class, org.deephacks.vals.proto.ProtoMessages.Val5Message.Builder.class);
      }

      // Construct using org.deephacks.jenc.proto.ProtoMessages.Val5Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mobileInfo_ = org.deephacks.vals.proto.ProtoMessages.TimeUnit.SECONDS;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        strings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.deephacks.vals.proto.ProtoMessages.internal_static_org_deephacks_jenc_Val5Message_descriptor;
      }

      public org.deephacks.vals.proto.ProtoMessages.Val5Message getDefaultInstanceForType() {
        return org.deephacks.vals.proto.ProtoMessages.Val5Message.getDefaultInstance();
      }

      public org.deephacks.vals.proto.ProtoMessages.Val5Message build() {
        org.deephacks.vals.proto.ProtoMessages.Val5Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.deephacks.vals.proto.ProtoMessages.Val5Message buildPartial() {
        org.deephacks.vals.proto.ProtoMessages.Val5Message result = new org.deephacks.vals.proto.ProtoMessages.Val5Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mobileInfo_ = mobileInfo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          strings_ = new com.google.protobuf.UnmodifiableLazyStringList(
              strings_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.strings_ = strings_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.deephacks.vals.proto.ProtoMessages.Val5Message) {
          return mergeFrom((org.deephacks.vals.proto.ProtoMessages.Val5Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.deephacks.vals.proto.ProtoMessages.Val5Message other) {
        if (other == org.deephacks.vals.proto.ProtoMessages.Val5Message.getDefaultInstance()) return this;
        if (other.hasMobileInfo()) {
          setMobileInfo(other.getMobileInfo());
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (!other.strings_.isEmpty()) {
          if (strings_.isEmpty()) {
            strings_ = other.strings_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureStringsIsMutable();
            strings_.addAll(other.strings_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.deephacks.vals.proto.ProtoMessages.Val5Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.deephacks.vals.proto.ProtoMessages.Val5Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .org.deephacks.jenc.TimeUnit mobileInfo = 1;
      private org.deephacks.vals.proto.ProtoMessages.TimeUnit mobileInfo_ = org.deephacks.vals.proto.ProtoMessages.TimeUnit.SECONDS;
      /**
       * <code>optional .org.deephacks.jenc.TimeUnit mobileInfo = 1;</code>
       */
      public boolean hasMobileInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .org.deephacks.jenc.TimeUnit mobileInfo = 1;</code>
       */
      public org.deephacks.vals.proto.ProtoMessages.TimeUnit getMobileInfo() {
        return mobileInfo_;
      }
      /**
       * <code>optional .org.deephacks.jenc.TimeUnit mobileInfo = 1;</code>
       */
      public Builder setMobileInfo(org.deephacks.vals.proto.ProtoMessages.TimeUnit value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        mobileInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .org.deephacks.jenc.TimeUnit mobileInfo = 1;</code>
       */
      public Builder clearMobileInfo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mobileInfo_ = org.deephacks.vals.proto.ProtoMessages.TimeUnit.SECONDS;
        onChanged();
        return this;
      }

      // optional string value = 2;
      private Object value_ = "";
      /**
       * <code>optional string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public String getValue() {
        Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder setValue(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      // optional int32 id = 3;
      private int id_ ;
      /**
       * <code>optional int32 id = 3;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 id = 3;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 3;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 3;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = 0;
        onChanged();
        return this;
      }

      // repeated string strings = 4;
      private com.google.protobuf.LazyStringList strings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStringsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          strings_ = new com.google.protobuf.LazyStringArrayList(strings_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public java.util.List<String>
          getStringsList() {
        return java.util.Collections.unmodifiableList(strings_);
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public int getStringsCount() {
        return strings_.size();
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public String getStrings(int index) {
        return strings_.get(index);
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStringsBytes(int index) {
        return strings_.getByteString(index);
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public Builder setStrings(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringsIsMutable();
        strings_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public Builder addStrings(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringsIsMutable();
        strings_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public Builder addAllStrings(
          Iterable<String> values) {
        ensureStringsIsMutable();
        super.addAll(values, strings_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public Builder clearStrings() {
        strings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strings = 4;</code>
       */
      public Builder addStringsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringsIsMutable();
        strings_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.deephacks.jenc.Val5Message)
    }

    static {
      defaultInstance = new Val5Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.deephacks.jenc.Val5Message)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_deephacks_jenc_Val5Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_deephacks_jenc_Val5Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\035src/main/resources/test.proto\022\022org.dee" +
      "phacks.jenc\"k\n\013Val5Message\0220\n\nmobileInfo" +
      "\030\001 \001(\0162\034.org.deephacks.jenc.TimeUnit\022\r\n\005" +
      "value\030\002 \001(\t\022\n\n\002id\030\003 \001(\005\022\017\n\007strings\030\004 \003(\t" +
      "*$\n\010TimeUnit\022\013\n\007SECONDS\020\001\022\013\n\007MINUTES\020\002B)" +
      "\n\030org.deephacks.jenc.protoB\rProtoMessage" +
      "s"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_deephacks_jenc_Val5Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_deephacks_jenc_Val5Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_deephacks_jenc_Val5Message_descriptor,
              new String[] { "MobileInfo", "Value", "Id", "Strings", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
